# ベクトルの定義

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
a.shape

(4,)

# 行列の定義

In [5]:
b = np.array([
    [1, 2],
    [3, 4]
])
b

array([[1, 2],
       [3, 4]])

In [6]:
b.shape

(2, 2)

# 特殊なベクトルと行列

In [8]:
c = np.zeros(8)
c

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
d = np.zeros((4, 3)) # 引数はタプルで指定する
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 単位行列
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 加減乗除

In [14]:
A = np.array([[1, 5], [4, -2]])
B = np.array([[2, -1], [7, 6]])
A + B

array([[ 3,  4],
       [11,  4]])

In [15]:
A - B

array([[-1,  6],
       [-3, -8]])

In [16]:
A * B

array([[  2,  -5],
       [ 28, -12]])

# 統計値の計算

In [19]:
# 合計
A.sum()

8

In [20]:
# 最大値
A.max()

5

In [21]:
# 最小値
A.min()

-2

In [22]:
# 平均値
np.average(A)

2.0

In [24]:
# 中央値（メジアン）
np.median(A)

2.5

In [25]:
# 分散
np.var(A)

7.5

In [26]:
# 標準偏差
np.std(A)

2.7386127875258306

# 逆行列

In [27]:
A = np.array([[1, 5], [4, -2]])
A

array([[ 1,  5],
       [ 4, -2]])

In [28]:
# 行列式を求める
# linalg（リニアアルジェブラの略、線形代数）
# det（デターミナント、行列）
a = np.linalg.det(A)
a

-22.000000000000004

In [29]:
# aが0でないときは逆行列が存在する
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.09090909,  0.22727273],
       [ 0.18181818, -0.04545455]])

In [31]:
# おおむね単位行列になる
np.dot(A, A_inv)

array([[ 1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00]])